import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[font]
normal = { family='FiraCode Nerd Font', style='Regular'}
bold = { family='FiraCode Nerd Font', style='Bold'}
italic = { family='FiraCode Nerd Font', style='Italic'}
bold_italic = { family='FiraCode Nerd Font', style='Bold Italic'}
offset = {x = 1, y = 1}
glyph_offset = {x = 1, y = 1}

[cursor]
style = { shape='Beam', blinking='Off'}

[window]
padding = { x = 25, y = 5}